version: "3.8"

services:
  whisper_local:
    build: ./transcribe-local
    container_name: whisper_local
    ports:
      - "5055:5055"
    environment:
      - WHISPER_MODEL=base

  send-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: send_worker
    env_file:
      - .env.production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"